name: Bookshelf CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Backend Tests
      run: |
        pytest test_main.py -v
        
    - name: Start FastAPI server
      run: |
        python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 5  # Даем серверу время на запуск
        
    - name: Run Frontend Tests
      run: |
        pytest test_frontend.py -v